/**
 * Diagnostics for silences between spoken chunks: one log line per chunk.
 *
 * All times are monotonic (performance.now), in seconds from the answer's
 * first text. The gap between two chunks (previous SoX exit to next SoX start)
 * is split into what playback was waiting for:
 *   text  - the sentence had not been generated by the LLM yet
 *   tts   - its text existed but Piper had not returned the audio
 *   sched - audio was ready, the player had not started it (polling, event loop)
 * SoX overhead is its run time minus the WAV duration (process start, ALSA open
 * and drain). lead/trail is the silence inside the WAV before/after the speech.
 */
import { performance } from "perf_hooks";

export type ChunkTiming = {
  queuedAt: number;
  synthStartAt?: number;
  readyAt?: number;
  playStartAt?: number;
  playEndAt?: number;
};

export const now = (): number => performance.now();

const s = (ms: number): string => (ms / 1000).toFixed(2);

export type ChunkReport = {
  index: number;
  total: number;
  chars: number;
  timing: ChunkTiming;
  answerStartAt: number;
  previousEndAt?: number;
  durationMs: number;
  leadMs?: number;
  trailMs?: number;
  waiting: number; // chunks queued after this one, not yet played
  waitingReady: number; // of those, with audio ready
  ttsActive: number;
  ttsPending: number;
};

/** Gap before a chunk, split into its causes (ms). */
export const splitGap = (
  previousEndAt: number,
  t: Required<Pick<ChunkTiming, "queuedAt" | "readyAt" | "playStartAt">>,
): { gap: number; text: number; tts: number; sched: number } => {
  const gap = Math.max(0, t.playStartAt - previousEndAt);
  const text = Math.max(0, Math.min(t.queuedAt, t.playStartAt) - previousEndAt);
  const tts = Math.max(0, Math.min(t.readyAt, t.playStartAt) - Math.max(previousEndAt, t.queuedAt));
  return { gap, text, tts, sched: Math.max(0, gap - text - tts) };
};

export const formatChunkReport = (r: ChunkReport): string => {
  const t = r.timing;
  const rel = (at?: number) => (at === undefined ? "?" : `+${s(at - r.answerStartAt)}`);
  const parts = [`[AudioTiming] chunk ${r.index}/${r.total} (${r.chars} chars)`];
  const slotWait = t.synthStartAt !== undefined ? t.synthStartAt - t.queuedAt : undefined;
  const synth = t.readyAt !== undefined && t.synthStartAt !== undefined ? t.readyAt - t.synthStartAt : undefined;
  parts.push(
    `queued ${rel(t.queuedAt)}` +
      (slotWait !== undefined && slotWait >= 50 ? `, TTS slot after ${s(slotWait)}s` : "") +
      (synth !== undefined ? `, synth ${s(synth)}s` : "") +
      `, ready ${rel(t.readyAt)}`,
  );
  if (t.playStartAt !== undefined && t.playEndAt !== undefined) {
    const overhead = t.playEndAt - t.playStartAt - r.durationMs;
    parts.push(
      `play ${rel(t.playStartAt)}..${rel(t.playEndAt)} (wav ${s(r.durationMs)}s, sox +${Math.round(overhead)}ms)`,
    );
  }
  if (r.previousEndAt !== undefined && t.readyAt !== undefined && t.playStartAt !== undefined) {
    const g = splitGap(r.previousEndAt, t as Required<ChunkTiming>);
    parts.push(
      `gap ${Math.round(g.gap)}ms = text ${Math.round(g.text)} + tts ${Math.round(g.tts)} + sched ${Math.round(g.sched)}`,
    );
  }
  if (r.leadMs !== undefined && r.trailMs !== undefined) {
    parts.push(`wav silence lead ${r.leadMs}ms trail ${r.trailMs}ms`);
  }
  parts.push(`queue ${r.waiting} waiting (${r.waitingReady} ready), tts ${r.ttsActive} active ${r.ttsPending} pending`);
  return parts.join(" | ");
};
